---
title: "Visualizations"
author: "Soumyadip"
date: "10/14/2019"
output: html_document
---
# TiduTuesday
## PowerLifting Github Page
https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-10-08 -->

```{r library-load, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(ggridges)
library(scales)
library(viridis)
library(forcats)
```

```{r data-load, message=FALSE, warning=FALSE}
ipf_lifts <- read_csv("data/ipf_lifts.csv")
```

```{r preview-data, message=FALSE, warning=FALSE}
glimpse(ipf_lifts)
```

## Lets see the effect of age on the max weight that can be lifted in squat
```{r fig.height=4, fig.width=8}
ipf_lifts %>%
  mutate(age_class = fct_rev(as.factor(age_class))) %>%
  filter(age_class != '5-12') %>%
  filter(age_class != '80-999') %>%
  drop_na(c(age_class,best3squat_kg)) %>%
  ggplot(aes(x=best3squat_kg,y=age_class,fill=factor(..quantile..))) +
  stat_density_ridges(geom="density_ridges_gradient",calc_ecdf = TRUE,
                      quantiles = 4,quantile_lines = TRUE,
                      na.rm = TRUE) +
  scale_fill_viridis(discrete = TRUE,name="Quartiles") +
  scale_x_continuous(limits = c(0,510),expand = c(0,0),labels=unit_format(unit="Kg")) +
  theme_bw() +
  labs(
    title = "Effects of Age on Weights (Squat)",
    x = "",
    y = "Age Classification"
  )
```
